### ISSUE TITLE
Spelling issues

### ISSUE THREAD

**Issue by boyraad300** [JBurlison/Pandaros.Settlers#1]
just a heads up on some spelling issues I've noticed in your language file
**line 87:**
    "Pandaros.Settlers.Miner": "A good machine can mine twice as fast as any human! Requires a good supply or wood or coal. Crank to start!",  
**should be** 
    "Pandaros.Settlers.Miner": "A good machine can mine twice as fast as any human! Requires a good supply **of** wood or coal. Crank to start!",  
**and line 35**
"Pandaros.Settlers.Miner": "Maining Machine",
**should be** 
"Pandaros.Settlers.Miner": "**Mining** Machine",

**Comment by boyraad300** [comment]
not game breaking or anything just wanted to help out

**Comment by JBurlison** [comment]
Thanks for the feedback! I will get it in next release!

**Comment by JBurlison** [comment]
Fixed [877dac6](https://github.com/JBurlison/Pandaros.Settlers/commit/877dac6b3fd1ea73286107648c7d4878c3059afe)
