### ISSUE TITLE
Issue: Beta does not work and breaks game.

### ISSUE THREAD

**Issue by Spartan3663** [JBurlison/Pandaros.Settlers#114]
I understand it's a beta and it is not stable but I also assume it's up for mass testing. My issue is nothing from the mod loads into the game and I cannot interact with almost every workbench in the game, in fact, the only workbench I can interact with is the science one. This happens even if I create a new game. The latest stable release works fine (which I am perfectly fine with waiting I just thought you should know of these problems).
Here is the log from the game:
[2019-06-11_06-45-49.txt](https://github.com/JBurlison/Pandaros.Settlers/files/3276070/2019-06-11_06-45-49.txt)

**Comment by JBurlison** [comment]
The beta is ment for the colony survival beta 7

**Comment by Spartan3663** [comment]
I see, sorry for not noticing.
