### ISSUE TITLE
Add Machinist maximum attempts to repair/refill before it will attempt to do the same to a different type of machine. 

### ISSUE THREAD

**Issue by boyraad300** [JBurlison/Pandaros.Settlers#12]
As it currently is if I have a lack of resources for one of my turrets the machinist will just stand there waiting for it even if it has the tools needed to repair/refill my other ones. Maybe after 3 attempts the Machinist will search for another different type of block to attempt to repair/refill.

**Comment by boyraad300** [comment]
also great work with this mod, the issues you put up yourself look crazy interesting and so far it adds a lot of fun content to the game :)

**Comment by JBurlison** [comment]
Thanks! I will put a fix in for this asap!

**Comment by JBurlison** [comment]
Resolved: https://github.com/JBurlison/Pandaros.Settlers/commit/f48df8711f3ea367fb5e85e523949f6e6e08ee3e
