### ISSUE TITLE
Make armor damage adjustments not affect health gains

### ISSUE THREAD

**Issue by RoniJames** [JBurlison/Pandaros.Settlers#14]
line 257 of Armor.cs needs a check for positive damage as is the case when you eat food. As it currently is eating food gives you a weird amount of health because of your armor. Thank you

**Comment by boyraad300** [comment]
also back in Turrets.cs on line 144 not sure if the ? added was a mistype
retval = TurretSettings[machineState.MachineType].Ammo.FirstOrDefault(ammo => !stockpile.Contains(ammo))**?**.Type;

**Comment by JBurlison** [comment]
Yes, that is a null check, https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-conditional-operators

**Comment by boyraad300** [comment]
can the return of FirstOrDefault be null since inventoryitem is not nullable? I'm getting an error when trying to compile it in VS

**Comment by JBurlison** [comment]
Fixed: https://github.com/JBurlison/Pandaros.Settlers/commit/61f5ffb26d8643555131e6292e1fad2922f7dcac

**Comment by JBurlison** [comment]
https://github.com/JBurlison/Pandaros.Settlers/commit/e01821182638530beb8f9a56dba73ce641c36d21
