### ISSUE TITLE
Maybe Issue - Maybe Not - Sling Turret

### ISSUE THREAD

**Issue by BlueRoomWebStudio** [JBurlison/Pandaros.Settlers#15]
I added some Turrets, not knowing what I was doing, I didn't add a Machinist until I figured out they needed maintenance. The Machinist would tend to it, and I saw the icons that are described here as he repaired, reloaded, etc. Then it got stuck on an icon that had a black background, and a silver dashed 's' shaped line with what looked to be a tiny propeller on the end of the line. I assumed it to mean it needed slings, but I had a lot of slings already. The crafting indicator continued to fill. The machinist continued to do it even after I picked up the turret, and I was only able to get him to quit when I picked up the machinist's table.

**Comment by JBurlison** [comment]
It means he cannot get to his next machine. He has to be able to stand next to them like crafters stand next to their crafting table. This will be fixed next release.

**Comment by BlueRoomWebStudio** [comment]
Wow that was fast. Thank you.

**Comment by BlueRoomWebStudio** [comment]
Awesome job on all of it by the way. I am thoroughly enjoying it.

**Comment by JBurlison** [comment]
Fixed this in latest release. Increased how far the machinists can reach.
