### ISSUE TITLE
Crash asked me to submit logs

### ISSUE THREAD

**Issue by airynd** [JBurlison/Pandaros.Settlers#17]
Here ya go!

I'm honestly not sure what I was doing at the time of the crash - I think I was just flying around, but not certain at this point.

[error.log](https://github.com/JBurlison/Pandaros.Settlers/files/1598794/error.log)
[output_log.txt](https://github.com/JBurlison/Pandaros.Settlers/files/1598795/output_log.txt)

**Comment by JBurlison** [comment]
Hello! I think you are looking for https://github.com/pipliz/ColonySurvival
