### ISSUE TITLE
Add Default localization

### ISSUE THREAD

**Issue by Khanx** [JBurlison/Pandaros.Settlers#21]
If you use a different localization of en-US or ru-RU the json appears.

Add a default localization when you use a different, for example use en-US.

![eses](https://user-images.githubusercontent.com/2260108/35988153-f8200d54-0cfd-11e8-963f-4bf40a4dfa8c.png)

**Comment by JBurlison** [comment]
Hello! this is actually a bug with the game. 

https://github.com/pipliz/ColonySurvival/issues/194

put an issue in here.
