### ISSUE TITLE
Machinist not working/ constant server error messages

### ISSUE THREAD

**Issue by zac21se** [JBurlison/Pandaros.Settlers#27]
Here's the log, I ran the server for just a few seconds as the file got large very quickly. 
[2018-02-21_22-10-59.txt](https://github.com/JBurlison/Pandaros.Settlers/files/1746680/2018-02-21_22-10-59.txt)

**Comment by JBurlison** [comment]
Thanks! I will have this fixed asap!

**Comment by JBurlison** [comment]
Let me know if the error messages have gone away in todays release.

**Comment by zac21se** [comment]
They have not, I tried uninstalling the game and trying again with a clean install on a new world but the error message was still there. I also tried on the original world and it gave the error message too, and the machinist were still not working, they usually just stand at the banner. 
[TEST 2018-02-22_13-37-57.txt](https://github.com/JBurlison/Pandaros.Settlers/files/1749488/TEST.2018-02-22_13-37-57.txt)
[Original 2018-02-22_13-39-10.txt](https://github.com/JBurlison/Pandaros.Settlers/files/1749489/Original.2018-02-22_13-39-10.txt)

**Comment by JBurlison** [comment]
this is in a new world?

**Comment by JBurlison** [comment]
I found the bug, im creating a release now that will fix your problem =)

**Comment by JBurlison** [comment]
https://github.com/JBurlison/Pandaros.Settlers/releases/tag/v0.7.2.0

Try this!
