### ISSUE TITLE
Help with pandaros mod, please. 

### ISSUE THREAD

**Issue by JudgeDraco** [JBurlison/Pandaros.Settlers#28]
I posted this on steam and was told to post it here instead so here it is.

This is after installing the pandaros mod. The game runs fine but my server log is this and it repeats like a million times a second... Not exagerating.
[2018-02-21_07-26-03.txt](https://github.com/JBurlison/Pandaros.Settlers/files/1750323/2018-02-21_07-26-03.txt)

**Comment by JBurlison** [comment]
https://github.com/JBurlison/Pandaros.Settlers/releases/tag/v0.7.2.0

New release fixes this!

**Comment by JudgeDraco** [comment]
Ok I just downloaded the new update that was release about 10 minutes ago and when I open my server exe I'm greeted by this. I moved the files directly form the zip to the mods file and clicked replace existing. Did I do something wrong?
![untitled](https://user-images.githubusercontent.com/36752129/36576164-f645cf94-181c-11e8-9e76-290cf8ad33bb.png)

**Comment by JudgeDraco** [comment]
Looks like it runs fine when I start up the server so idk what the exceptions are for. ![untitled1](https://user-images.githubusercontent.com/36752129/36576514-2625f69c-181f-11e8-948d-fa3d4d1906de.png)

**Comment by JBurlison** [comment]
Yeah githubs API is down today for some reason. I cant even add code to it., they have to resolve this.

The good news is the bug is officially squashed!
