### ISSUE TITLE
Sugestion: Builders wand

### ISSUE THREAD

**Issue by Khanx** [JBurlison/Pandaros.Settlers#30]
I suggest making the wand based on the WorldEdit plugin from minecraft

Wiki: http://wiki.sk89q.com/wiki/WorldEdit
Video example: https://www.youtube.com/watch?v=lc42-LvvwbY

**Comment by JBurlison** [comment]
Thanks! Maybe I will make a advanced builders wand, the current one is simple, this one is far more complex but it is something I can defiantly do!

**Comment by Khanx** [comment]
Right now i'm working in a mod for the advanced version of the wand.

But not an extension of Settlers.
