### ISSUE TITLE
No siege mode during days even during attacks

### ISSUE THREAD

**Issue by PhilipBernhardsson** [JBurlison/Pandaros.Settlers#32]
Since there is no siege mode during daytime you can just close off the entrance to your base even if a boss comes during the daytime and completely cheese the entire boss wave.

**Comment by JBurlison** [comment]
Fixed in 0.8.0.0

**Comment by JBurlison** [comment]
Bosses will no longer die if you block their path. They will teleport to the next valid position in their path to prevent cheesing bosses via path blocking.
