### ISSUE TITLE
Builders Wand

### ISSUE THREAD

**Issue by Acefoxx76** [JBurlison/Pandaros.Settlers#33]
I've encountered an issue with the Horizontal setting on the wand not wanting to place blocks on one side of a block. It will place on top, on bottom and on the side but not the other side.

![366090_screenshots_20180320200816_1](https://user-images.githubusercontent.com/37602004/37689410-25e39480-2c7b-11e8-97a2-32ff59220f89.jpg)
![366090_screenshots_20180320200844_1](https://user-images.githubusercontent.com/37602004/37689411-25f0a7b0-2c7b-11e8-9fe6-2854a465273a.jpg)
![366090_screenshots_20180320200859_1](https://user-images.githubusercontent.com/37602004/37689412-2600cc6c-2c7b-11e8-951e-a83b7af3a225.jpg)
![366090_screenshots_20180320200906_1](https://user-images.githubusercontent.com/37602004/37689413-260d6080-2c7b-11e8-943a-828d00f20f4d.jpg)
![366090_screenshots_20180320200911_1](https://user-images.githubusercontent.com/37602004/37689414-266b9e5c-2c7b-11e8-862a-c03c2ba90dc8.jpg)

**Comment by JBurlison** [comment]
Fixed in 0.8.0.0
