### ISSUE TITLE
Offline Mode Bug?

### ISSUE THREAD

**Issue by Horner14** [JBurlison/Pandaros.Settlers#34]
I left a friends server to test the offline mode quickly and when I came back online, I found all my colonists walking up to the flag. There were no colonists or guards out, just 5 standing around the flag and although I was being attacked by Zombies, none of my colonists went back to their normal positions

**Comment by JBurlison** [comment]
Thanks! I will take a look tonight!

**Comment by JBurlison** [comment]
Fixed https://github.com/JBurlison/Pandaros.Settlers/releases/tag/v0.8.0.6
