### ISSUE TITLE
Settlers dying and not coming of colonists count

### ISSUE THREAD

**Issue by Gazzer159** [JBurlison/Pandaros.Settlers#35]
Hello,

Having an issue where settlers where coming to my colony but when they died they did not come off the colonists figure but registered as unemployed. This may have been as a monster was at my flag at the time and they died quickly but it meant i would have needed to place down new beds to replace them.

**Comment by JBurlison** [comment]
Resolved in https://github.com/JBurlison/Pandaros.Settlers/releases/tag/v0.8.0.6
