### ISSUE TITLE
Saying two settlers join but only one did

### ISSUE THREAD

**Issue by DemKitten** [JBurlison/Pandaros.Settlers#36]
I have an issue on 0.8.0.3 where a settler will join and it will say that one settler joined in chat but there will be two settlers added to the colonist count. This is a huge issue because i have to make 2 beds for 1 colonist. i can manually fix it by going into the NPC file in my save games and deleting a extra id for the colonist that joined.

**Comment by JBurlison** [comment]
Resolved in https://github.com/JBurlison/Pandaros.Settlers/releases/tag/v0.8.0.6
