### ISSUE TITLE
Offline Colonies Causing Zombies to Spawn Inside Base

### ISSUE THREAD

**Issue by Horner14** [JBurlison/Pandaros.Settlers#49]
I am not too sure how the Offline Colonies is coded but it seems to be that if I don't join straight away from when my friend launches the server and my colony goes into offline mode, as soon as I do load in my colonists are being killed by Zombies straight away and there are Zombies inside my base even though there's only one entrance and none of the guards by the entrance have died.
It seems to be the way the offline mode works that allows zombies to spawn in the area where my base is.

**Comment by JBurlison** [comment]
It should kill his zombies when he logs out. None should be spawning for you because when offline colonies are disabled it makes the game think you have no colonists. I will look into it
