### ISSUE TITLE
Audio not being played in game

### ISSUE THREAD

**Issue by 5aturat3dmark** [JBurlison/Pandaros.Settlers#51]
Entities and blocks from the mod (zombie moans, colonists talking, mining machine 'clinks', gate moving, etc.) are not played in game. Other machines work fine with audio that is sourced from the base game (turrents for instance) and it appears the amount of missing audio lines up with the tracks listed in audioFiles.json.

I noticed when looking at the solution in VS, I think this is caused by there being inaccurate string concatenations for the audioFiles.json. For instance in MonsterManager.cs in OnUpdate(), in the line `ServerManager.SendAudio(monster.Value.Position, GameLoader.NAMESPACE + "ZombieAudio");` ZombieAudio is missing the period in front of it, so when it concatenates, it would read `"Pandaros.SettlersZombieAudio"` to which obviously does not exist, thus not being able to ready the audio script. saw the same with TalkingAudio in SettlerManager.cs.

**Comment by JBurlison** [comment]
ahhh thanks! I will fix this!
