### ISSUE TITLE
Question: Are colonists suppose to take up the machinist's beds?

### ISSUE THREAD

**Issue by 5aturat3dmark** [JBurlison/Pandaros.Settlers#52]
Sorry if the question seems weird, but i noticed that over time, whenever new settlers would show up they would stick around and sleep in beds at night and hold occupations like colonists should do, despite the instance that I would already be at max size for my colony based on the number of beds I had that were already all "occupied". 

For example, I would have 300 beds, so the max would be 300 colonists. But when i placed down a job block for them to work at, they would occupy the block like normal and stay around in the colony, despite there technically being no more beds in the colony. So now there would be 301 colonists, but still only 300 beds. This so far dosen't have any impact on my colony so far as breaking things or causing glitches so I wasn't sure if this was intended or not.

What peaked my interest was that i saw that essentially these overflowing colonists would occupy the "occupied" beds that the machinists would own. Of course, the machinists never actually sleep in the beds, so those beds are vacant at night for the extra colonists to sleep in.

My question is that is this suppose to be able to happen? it seems that it could cause some complications in colony calculations or whatnot since there are technically more colonists than the colony can support. For instance, I keep running into the issue of some colonists would walk across the entire colony to one of my outpost buildings to sleep in the vacant beds because the majority of those beds were for the machinist that work the defense system, but the other colonists like my farmers and crafters would walk all the way over and occupy those beds instead, causing large amounts of time to be wasted in traveling.

**Comment by 5aturat3dmark** [comment]
Also I apologize if it seems that I am just hitting you with a bunch of issues all of a sudden and distracting you from working, especially since I cannot really provide much help in solving the bugs directly. I figured it would be better to list them all as I find them so that way it would be easier to bundle up several bug fixes per update and make bug handling much easier from your end. 

Thanks again for your awesome work with this mod. It really makes the game so much better and more immersive with all the content provided from the mod!

**Comment by JBurlison** [comment]
lol no problem man! Yes, they just dont sleep because there is no day/night machinists. But its in the games code that there be 1 bed per colonist.
