### ISSUE TITLE
[0.8.1.5] Crafters can't make windows / double windows

### ISSUE THREAD

**Issue by 5aturat3dmark** [JBurlison/Pandaros.Settlers#53]
Whenever the crafters attempt to make either windows or double windows, they go to the crate to get supplies but then go back to the crafting bench and stand there, doing nothing.

Re-prioritizing or resizing quantity does not change this outcome and the crafters are stuck on attempting to craft the windows, thus holding up all crafting for the colony. Lowering the priority or reducing the quantity demanded makes them immediately cease attempts at making these items and skip over to continue crafting everything else.

**Comment by JBurlison** [comment]
Thanks for the report! I am looking into it now!

**Comment by BrightExistence** [comment]
I can verify this experience, and can add that changing the requirement for window in the settler's crafting.json file from "glass" to "Pandaros.Settlers.AutoLoad.glass" fixed this issue for me. (The requirement "window" in the doublewindow recipe was also changed to "Pandaros.Settlers.AutoLoad.window" and again fixed the doublewindow crafting issue.

**Comment by JBurlison** [comment]
I am doing a release tonight, I will have this fixed. Thanks for the report guys!
