### ISSUE TITLE
texture

### ISSUE THREAD

**Issue by gordon199412** [JBurlison/Pandaros.Settlers#56]
so i have installed your mod it look realy nice that first make the game more complete. 
so when i did puti t in the fence did not have any texture. so i fix that with one of you fixs. bud when i installed your fix the sun light got more brigther so there is almost noting to see and all the bed where black. i have try tp reinstal the game and the mod dont work i have try to put the fix in first and then the last version of the mod did not work not only my beds are black bud the spam point for the colone is black to.

**Comment by JBurlison** [comment]
Fixed!!
