### ISSUE TITLE
Lag/Slowdown Near Mountains

### ISSUE THREAD

**Issue by pdexpdex** [JBurlison/Pandaros.Settlers#60]
I am experiencing major lag/stutter when I get near a mountain with Settlers installed.  Specifically, I have to be near a mountain AND face toward the mountain.  It is severe enough that I can't really play at all near the mountains.

I have no other mods installed.  I did have others installed, but deleted them and started a new world to test it on a second world as well.  I have installed by the I'm playing a single player world.  

When I use 'flight' to move underground, I notice huge cubes of what looks like vertical half slabs of grass.  They can be broken and can have a torch attached to them. They also seem to have a horizontal half block selection box when targeted.  If I break a few, then quit and reload, the particular cube (chunk? that would probably be the Minecraft term for it...) that I modified changes to stone instead of the weird half slabs of grass.  

If I remove Settlers and load back up the same world, the lag stops, and if I fly underground, the strange little cubes/chunks underground are gone.

There are some screenshots attached to try to clarify what I mean.

Mysterious Subterranean Cubes:
![20180513000959_1](https://user-images.githubusercontent.com/39231499/39964202-d3a4d122-5644-11e8-872c-dabcce5cd09e.jpg)

Vertical Half-Slabs of Grass (seen after flying into a cube and clearing some space around me):
![20180513000924_1](https://user-images.githubusercontent.com/39231499/39964204-d7f4e992-5644-11e8-8ede-7c98c7b91fa8.jpg)

After reload, the cube/chunk I flew into and modified has become stone:
![20180513002236_1](https://user-images.githubusercontent.com/39231499/39964205-daf881d0-5644-11e8-95fe-55fd4a710aa5.jpg)

Removing Settlers removes the weird cubes/chunks:
![20180513003624_1](https://user-images.githubusercontent.com/39231499/39964250-12270ef0-5646-11e8-919f-31d18f61b5b7.jpg)

I hope this is enough information to try to track down the issue... or to tell me I'm nuts and the problem is with my setup somehow.

**Comment by 5aturat3dmark** [comment]
I wasn't able to replicate the lag or the odd slab block generation with my world following your description.

I can only think of two things that might result in what looks to be corrupt chunk loading:
1) Do you have the latest version of the mod installed? Sometimes for certain people, the mod dosen't
auto-update like you would think it does and just keeps the mod on the same version within the mods folder. You can also do a manual update if you are not sure if it is up-to-date.
2) Have you constructed or altered the terrain near or in the area at all? I recall reading in on of the weekly update blogs that there were sometimes issues with colonies in regards to when terrain changes were made by the player and some mechanics would not work correctly (zombie spawns, colonists pathfinds).

If you weren't able to verify these two possibilities as being the cause of the lag and random block generation, then it might be a corruption of the chunks in your save.

Sorry if that wasn't much help, as I rarely get these kinds of issues with my saves, so I am unsure of how to maximize the amount of solutions to this issue.

**Comment by pdexpdex** [comment]
I actually attempted this with two different methods of installing the mod.  I first installed it with the CS Mod Manager, and got the lag and weird structures.  I was afraid it might be the result of a corrupt install, so I deleted the mod files and  downloaded the files manually and put them in the mod folder, then started up again and created a new world.  Prior to either of these two attempts (which were both fresh installs of the mod, so I doubt there was any worry of an old version being the problem), I had actually tried to install the mod on my laptop and experienced the same lag on that machine.  I figured it was my laptop that was the problem - I have some significant lag on my modded Minecraft install on it that doesn't appear on my desktop - so I didn't do much more testing.  When it happened on my desktop as well, I started poking around more, and found the weird under mountain chunks.  

As to construction or alteration, with both worlds I created, I noticed the lag while searching for somewhere to start building my base, so I had made no alterations in the world at all, apart from enabling flight to make finding a spot easier.  The first modifications I made to either map was to see if the weird vertical slabs were destructable and if I could plant a torch on them.  

Just to be 100% sure, I just created a third world and found the same symptoms.  No noticeable lag until I find a mountain, then a large quantity of weird underground chunks when I drop below the surface.

**Comment by KySoto** [comment]
I dont know about the slabs part of it (i havent enabled any cheats to fly underground or anything) but i only installed this mod and the api mod, and when i look at mountains, i get a significant slowdown as well.

**Comment by JBurlison** [comment]
Do you guys have any other mods installed? I do nothing with the renderer so It could be another mod.

**Comment by KySoto** [comment]
i personally am using the Colony Survival Mod Manager, and i got NewColonyAPI version 1.2.3.1 and Pandaros.Settlers version 0.8.1.7. i ensured that i had no other mods by deleting everything in my mods folder (which i found out caused an error and i had to validate my game cache to fix.)

**Comment by sda963109** [comment]
still have same problem in new patch. so sad:(

**Comment by sda963109** [comment]
well I just found a way to solve this. though I don't actually know what cause this issue.
bad english so explain with images
![default](https://user-images.githubusercontent.com/39833298/41202868-e8752b82-6d01-11e8-8c33-1a8bcd424520.png)
then create a localization file for the mod
![default](https://user-images.githubusercontent.com/39833298/41202912-c99bb162-6d02-11e8-8ab5-35d940ee0cb5.png)

don't know if it work for everyone. but it does in my case.

**Comment by perkh1** [comment]
on the issue of the vertical grass tiles they seem to appear in a fairly large bunch which generates an incredible large amount of lagg, see picture
![bilde](https://user-images.githubusercontent.com/40396734/41604775-4feb5c98-73e0-11e8-8460-6333d2ca6a71.png)

**Comment by JBurlison** [comment]
Can you attach your world save to the ticket please in a zip file?

**Comment by pipliz** [comment]
So I looked into this at request of @JBurlison and it is an issue in the base game that just happens to be exposed by mods. It's been fixed for the next update of the game (0.6.3.0).

**Comment by JBurlison** [comment]
When the new patch comes out for colony survival, you will need to re-make your world.
