### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by Khanx** [JBurlison/Pandaros.Settlers#62]
Hi Pandaros,

when i start a server with the mod i get:

NullReferenceException: Object reference not set to an instance of an object
  at Pandaros.Settlers.VersionChecker.WriteVersionsToConsole () [0x00000] in <filename unknown>:0 
  at Pandaros.Settlers.GameLoader.AfterStartup () [0x00000] in <filename unknown>:0 
  at ModLoader.TriggerCallbacks (EModCallbackType type) [0x00000] in <filename unknown>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Pipliz.Log:WriteExceptionInternal(String, Exception)
Pipliz.Log:WriteException(String, Exception, EModCallbackType, String)
ModLoader:TriggerCallbacks(EModCallbackType)
UnityWrapper:Start()

I attach you the log.
[Sever.Log.txt](https://github.com/JBurlison/Pandaros.Settlers/files/2035235/Sever.Log.txt)

**Comment by JBurlison** [comment]
Thanks this was a issue with my update server being down, it should be all set now.
