### ISSUE TITLE
Mod doesn't work with new update

### ISSUE THREAD

**Issue by ArabellaBlack** [JBurlison/Pandaros.Settlers#63]
What now?

**Comment by Cruber** [comment]
Agreed, update?

**Comment by JBurlison** [comment]
I am working to get it updated! stay tuned!

**Comment by JBurlison** [comment]
Added as a part of:

https://github.com/JBurlison/Pandaros.Settlers/projects/1

**Comment by Jacist** [comment]
Any idea as to how long the update will take? I'm  not trying to rush, just curious if  I should wait to wipe my server for another few days or if it's going to be longer.
