### ISSUE TITLE
[Minor] [0.8.1.10] Colored Carpet limits reset upon world load

### ISSUE THREAD

**Issue by 5aturat3dmark** [JBurlison/Pandaros.Settlers#65]
I noticed a while back that every time you loaded a world, the dyer table would reset all of the colored carpet limits back to 2. I would change it to say 50 then save and exite the world, then log back in and it would always reset back to 2. This seems like an issue with how it is saving the client custom limits in the settings maybe?

I would have mentioned this issue earlier, but tbh i only use the dyer every now and then and had not had any use of them recently until now.

**Comment by JBurlison** [comment]
Fixed: https://github.com/JBurlison/Pandaros.Settlers/commit/2c0707150fa17e69ab103186c110c5c57b86b4f0
