### ISSUE TITLE
Idea: Crafting max & min

### ISSUE THREAD

**Issue by Khanx** [JBurlison/Pandaros.Settlers#95]
Let players define a **min** and **max** amount of items to craft instead of only the amount of items to craft.

For each recipe, a player can set a minimun amount and maximun amount.

How works:

if there is a recipe which the amount of items crafted are lower than the minimun then craft
else craft a item which is lower than the maximun.

In both cases take into acount the priority of the recipe.

PS: If you can put priority for minimun and other priority for maximun will be better.

**Comment by JBurlison** [comment]
Cant be done
