### ISSUE TITLE
Idea: Colonies growth

### ISSUE THREAD

**Issue by Khanx** [JBurlison/Pandaros.Settlers#96]
Each colony can have something like a lvl: http://worldonline.wikia.com/wiki/Buildings

Village lvl 1, lvl 2, lvl 3

Town lvl 1, lvl 2, lvl 3

Each lvl has a restrictions & need X things to upgrade to the next lvl.

This can be use to give the effect that a colony has to grown, and pass through eras (cultivation -> copper -> iron -> machines)

For example:

Player starts with a village lvl 1.

Village lvl 1:

Restrictions:

- Guards: Sling

- Research: Only can research Wheat[including grinder & baker] & herbs

- Max amount of 25 colonist

Need for next upgrade:

- Have more than 200 food

- All the research

- Max amount of colonist (25)

Village lvl 2:

Restrictions:

- Guards: Bow

- Reseach: BronzeAnvil, bows, ...

- Max amount of 50 colonist

Need for next upgrade:

- Have 10 bows and 200 arrows

- All the research

- Max amount of colonist (50)

...

**Comment by JBurlison** [comment]
Basically implemented by the devs.
