### ISSUE TITLE
Idea: Buildings

### ISSUE THREAD

**Issue by Khanx** [JBurlison/Pandaros.Settlers#98]
You can make “standard” blueprints that add things to your colony like upgrade production of X jobs inside X building from X blueprint, unlock jobs or research.

Some buildings: http://worldonline.wikia.com/wiki/Buildings

For example: You can use the building of “bathroom” to increase the sanity of your colony to increase the happiness.

Other option is to be able to create special buildings when X items are placed inside of them. For example to make a bathroom you need to add 3 toilets inside the build.

**Comment by JBurlison** [comment]
Done.
